site_name: Disconomy Docs
site_url: https://distortedpumpkin.github.io/disconomy-docs

nav:
    - Home: index.md
    - Getting Started: 
      - Getting Started: getting-started/getting-started.md
      - Making Money: getting-started/making-money.md
    - Businesses: 
      - Setup/Usage: 
        - Factory: businesses/setup-usage/factory.md
        - Mine: businesses/setup-usage/mine.md
        - Power Plant: businesses/setup-usage/power-plant.md
      - Work: 
        - Jobs: businesses/work/jobs.md
        - Working: businesses/work/working.md
      - Partnerships: 
        - Impacts/Benifits: businesses/partnerships/impacts-benefits.md
    - Market:
      - Prices: market/prices.md
    - Premium:
      - Premium Perks: premium/premium.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
markdown_extensions:
  - toc:
      permalink: true
      title: On this page
