site_name: Disconomy Docs
site_url: https://disconomy.app/docs
nav:
    - Home: index.md
    - Getting Started: getting-started.md
    - Businesses: 
      - Partnerships: 
        - Impacts/Benifits: businesses/partnerships/impacts-benifits.md
      - Setup/Usage: 
        - Factory: businesses/setup-usage/factory.md
        - Mine: businesses/setup-usage/mine.md
        - Power Plant: businesses/setup-usage/power-plant.md
      - Work: 
        - Jobs: businesses/work/jobs.md
        - Working: businesses/work/working.md
theme:
  name: material
    
